(* This file has been auto-generated by the SPL compiler *)
type t = [
  |`Become_Primary
  |`Become_Replica
  |`BeginViewChange
  |`Initialize
  |`Recover
]

let string_of_statecall (x:t) = match x with
  |`Become_Primary -> "Become_Primary"
  |`Become_Replica -> "Become_Replica"
  |`BeginViewChange -> "BeginViewChange"
  |`Initialize -> "Initialize"
  |`Recover -> "Recover"

