(* This file has been auto-generated by the SPL compiler *)
type t = [
  |`Finish_Recovering
  |`Receive_Commit
  |`Receive_Doviewchange
  |`Receive_Prepare
  |`Receive_Prepareok
  |`Receive_Primaryrecoveryresponse
  |`Receive_Recovery
  |`Receive_Recoveryresponse
  |`Receive_Request
  |`Receive_Startview
  |`Receive_Startviewchange
  |`Send_Commit
  |`Send_Doviewchange
  |`Send_Prepare
  |`Send_Prepareok
  |`Send_Recovery
  |`Send_Recoveryresponse
  |`Send_Reply
  |`Send_Startview
  |`Send_Startviewchange
]

let string_of_statecall (x:t) = match x with
  |`Finish_Recovering -> "Finish_Recovering"
  |`Receive_Commit -> "Receive_Commit"
  |`Receive_Doviewchange -> "Receive_Doviewchange"
  |`Receive_Prepare -> "Receive_Prepare"
  |`Receive_Prepareok -> "Receive_Prepareok"
  |`Receive_Primaryrecoveryresponse -> "Receive_Primaryrecoveryresponse"
  |`Receive_Recovery -> "Receive_Recovery"
  |`Receive_Recoveryresponse -> "Receive_Recoveryresponse"
  |`Receive_Request -> "Receive_Request"
  |`Receive_Startview -> "Receive_Startview"
  |`Receive_Startviewchange -> "Receive_Startviewchange"
  |`Send_Commit -> "Send_Commit"
  |`Send_Doviewchange -> "Send_Doviewchange"
  |`Send_Prepare -> "Send_Prepare"
  |`Send_Prepareok -> "Send_Prepareok"
  |`Send_Recovery -> "Send_Recovery"
  |`Send_Recoveryresponse -> "Send_Recoveryresponse"
  |`Send_Reply -> "Send_Reply"
  |`Send_Startview -> "Send_Startview"
  |`Send_Startviewchange -> "Send_Startviewchange"

