(* This file has been auto-generated by the SPL compiler *)
type t = [
  |`Deliver_Commit
  |`Deliver_Doviewchange
  |`Deliver_Prepare
  |`Deliver_Prepareok
  |`Deliver_Primaryrecoveryresponse
  |`Deliver_Recovery
  |`Deliver_Recoveryresponse
  |`Deliver_Request
  |`Deliver_Startview
  |`Deliver_Startviewchange
  |`Send_Commit
  |`Send_Doviewchange
  |`Send_Prepare
  |`Send_Prepareok
  |`Send_Recovery
  |`Send_Recoveryresponse
  |`Send_Reply
  |`Send_Startview
  |`Send_Startviewchange
]

let string_of_statecall (x:t) = match x with
  |`Deliver_Commit -> "Deliver_Commit"
  |`Deliver_Doviewchange -> "Deliver_Doviewchange"
  |`Deliver_Prepare -> "Deliver_Prepare"
  |`Deliver_Prepareok -> "Deliver_Prepareok"
  |`Deliver_Primaryrecoveryresponse -> "Deliver_Primaryrecoveryresponse"
  |`Deliver_Recovery -> "Deliver_Recovery"
  |`Deliver_Recoveryresponse -> "Deliver_Recoveryresponse"
  |`Deliver_Request -> "Deliver_Request"
  |`Deliver_Startview -> "Deliver_Startview"
  |`Deliver_Startviewchange -> "Deliver_Startviewchange"
  |`Send_Commit -> "Send_Commit"
  |`Send_Doviewchange -> "Send_Doviewchange"
  |`Send_Prepare -> "Send_Prepare"
  |`Send_Prepareok -> "Send_Prepareok"
  |`Send_Recovery -> "Send_Recovery"
  |`Send_Recoveryresponse -> "Send_Recoveryresponse"
  |`Send_Reply -> "Send_Reply"
  |`Send_Startview -> "Send_Startview"
  |`Send_Startviewchange -> "Send_Startviewchange"

