(* This file has been auto-generated by the SPL compiler *)
exception Bad_statecall

type s = [
  |`Send_Recovery
  |`Send_Startviewchange
  |`Deliver_Doviewchange
  |`Send_Recoveryresponse
  |`Send_Startview
  |`Send_Commit
  |`Deliver_Prepare
  |`Deliver_Recoveryresponse
  |`Deliver_Primaryrecoveryresponse
  |`Deliver_Prepareok
  |`Deliver_Commit
  |`Send_Reply
  |`Send_Prepare
  |`Deliver_Recovery
  |`Send_Prepareok
  |`Deliver_Startviewchange
  |`Send_Doviewchange
  |`Deliver_Startview
  |`Deliver_Request
]

type t
val init : q:int -> t
val pagefn : out_channel -> unit
val set_cfn : t -> (unit -> (out_channel * in_channel)) -> unit
val tick : t -> [> s] -> t
